import type { Metadata } from "next";
import Link from "next/link";
import LegalDocument, { type LegalSection } from "../components/LegalDocument";
import PublicInfoShell from "../components/PublicInfoShell";

export const metadata: Metadata = {
  title: "Ketentuan Layanan",
  description: "Aturan penggunaan akun, transaksi, pembayaran, sengketa, dan layanan AlidPay.",
};

const sections: LegalSection[] = [
  { id: "persetujuan", title: "Persetujuan dan kelayakan", content: <><p>Dengan membuat akun atau memakai AlidPay, kamu menyetujui ketentuan ini dan <Link href="/privasi">Kebijakan Privasi</Link>. Kamu harus memiliki kecakapan hukum untuk membuat perjanjian dan memberikan informasi yang benar, lengkap, serta terkini.</p><p>Jika memakai layanan untuk organisasi, kamu menyatakan berwenang mengikat organisasi tersebut.</p></> },
  { id: "akun", title: "Akun dan keamanan", content: <><p>Satu akun hanya boleh digunakan oleh pemilik yang sah. Kamu bertanggung jawab menjaga kredensial, perangkat, dan akses akun; memberi informasi akurat; serta segera melaporkan akses tanpa izin. Kami dapat meminta verifikasi tambahan, membatasi fitur, atau menahan tindakan berisiko untuk melindungi pengguna.</p><p>Dilarang menjual, meminjamkan, membuat identitas palsu, atau menggunakan akun orang lain tanpa izin.</p></> },
  { id: "transaksi", title: "Membuat dan menyetujui transaksi", content: <><p>Pembuat transaksi wajib menjelaskan objek, harga, pihak, pengiriman/pemenuhan, tenggat, dan syarat lain dengan jelas. Pihak penerima harus memeriksa detail sebelum menyetujui. Persetujuan elektronik dan aktivitas yang tercatat di AlidPay dapat digunakan sebagai bukti proses transaksi.</p><p>AlidPay menyediakan alur dan pencatatan transaksi, tetapi tidak menjadi penjual, pembeli, produsen, kurir, atau penjamin kualitas barang/jasa.</p></> },
  { id: "pembayaran-dana", title: "Pembayaran, status dana, dan biaya", content: <><p>Pembeli membayar melalui penyedia pembayaran yang tersedia. Status pembayaran baru dianggap berhasil setelah diverifikasi oleh sistem AlidPay dari notifikasi penyedia; tampilan atau klaim dari sisi pengguna bukan bukti pembayaran.</p><p>Istilah “dana ditahan” pada aplikasi menjelaskan status operasional transaksi dan pencatatan internal. Istilah itu bukan klaim bahwa AlidPay merupakan penyelenggara escrow berizin. Identitas penyedia pembayaran, biaya layanan, pajak, batas, estimasi waktu, serta total yang dibayar dan diterima akan ditampilkan sebelum tindakan terkait dikonfirmasi.</p></> },
  { id: "kewajiban", title: "Kewajiban pembeli dan penjual", content: <><ul className="list-disc"><li><strong>Pembeli</strong> wajib membayar sesuai kesepakatan, memberikan informasi penerimaan yang benar, memeriksa pemenuhan, dan mengajukan masalah dalam waktu yang tersedia.</li><li><strong>Penjual</strong> wajib memiliki hak menjual, memberikan deskripsi jujur, memenuhi pesanan sesuai kesepakatan, menyimpan bukti, dan menanggapi masalah tepat waktu.</li><li><strong>Kedua pihak</strong> wajib berkomunikasi dengan itikad baik dan tidak memanipulasi bukti atau status transaksi.</li></ul></> },
  { id: "larangan", title: "Aktivitas yang dilarang", content: <><p>Dilarang memakai AlidPay untuk barang/jasa ilegal; penipuan; pencucian uang; pendanaan terlarang; eksploitasi; pelanggaran hak kekayaan intelektual; transaksi fiktif; manipulasi sistem, ulasan, atau bukti; akses tanpa izin; penyebaran malware; serta upaya menghindari pemeriksaan keamanan atau batas layanan.</p><p>Kami dapat menolak, menunda, membekukan, membatalkan, atau melaporkan aktivitas yang patut diduga melanggar hukum atau ketentuan ini.</p></> },
  { id: "sengketa", title: "Pembatalan, pengembalian, dan sengketa", content: <><p>Ajukan masalah melalui halaman transaksi dan sertakan bukti yang relevan. Kelayakan pembatalan atau pengembalian bergantung pada status transaksi, bukti, metode pembayaran, dan keputusan sengketa; pengembalian tidak dijanjikan otomatis. Selama peninjauan, status dana dapat tetap ditahan.</p><p>AlidPay dapat meminta keterangan, menetapkan tenggat, dan mengambil keputusan berdasarkan detail transaksi, bukti, komunikasi, status pemenuhan, serta aturan yang berlaku. Hasil dapat berupa pelepasan dana kepada penjual, pengembalian penuh/sebagian kepada pembeli, atau tindakan lain yang wajar. Waktu dana kembali juga dapat dipengaruhi penyedia pembayaran. Keputusan internal tidak menghilangkan hak hukum yang tidak dapat dikesampingkan.</p></> },
  { id: "tanggung-jawab", title: "Ketersediaan dan batas tanggung jawab", content: <><p>Kami berupaya menjaga layanan aman dan tersedia, tetapi pemeliharaan, insiden, pihak ketiga, atau keadaan di luar kendali dapat menyebabkan gangguan. Sejauh diizinkan hukum, AlidPay tidak bertanggung jawab atas kerugian tidak langsung, kehilangan peluang, kualitas objek transaksi, atau tindakan pengguna dan pihak ketiga.</p><p>Tidak ada bagian ketentuan ini yang membatasi tanggung jawab yang secara hukum tidak boleh dibatasi atau hak konsumen yang wajib berlaku.</p></> },
  { id: "penangguhan", title: "Penangguhan dan penghentian", content: <><p>Kamu dapat berhenti menggunakan layanan setelah kewajiban dan transaksi terbuka diselesaikan. Kami dapat membatasi atau menutup akun karena risiko keamanan, pelanggaran, kewajiban hukum, data tidak valid, atau penyalahgunaan. Sebelum penutupan, dana dan sengketa yang ada akan ditangani sesuai hukum dan status transaksi.</p></> },
  { id: "umum", title: "Kekayaan intelektual, hukum, dan perubahan", content: <><p>Merek, desain, perangkat lunak, dan konten AlidPay dilindungi dan tidak boleh disalin atau digunakan tanpa izin. Kamu tetap memiliki kontenmu dan memberi AlidPay izin terbatas untuk memprosesnya demi menyediakan layanan.</p><p>Ketentuan ini tunduk pada hukum Republik Indonesia. Sengketa dengan AlidPay diupayakan lebih dahulu melalui musyawarah dan kanal bantuan, tanpa mengurangi forum atau hak yang diwajibkan hukum.</p><p>Kami dapat memperbarui ketentuan ini. Perubahan material akan diberitahukan jika diwajibkan. Pertanyaan dapat diajukan melalui <Link href="/bantuan#hubungi-kami">Pusat Bantuan</Link>.</p></> },
];

export default function TermsPage() {
  return (
    <PublicInfoShell eyebrow="Legal · Ketentuan" title="Aturan main yang jelas." description="Hak, kewajiban, dan batas tanggung jawab setiap pihak dalam memakai AlidPay.">
      <LegalDocument updatedAt="29 Agustus 2026" summary="Gunakan AlidPay secara jujur, periksa rincian biaya dan metode pembayaran sebelum menyetujui transaksi, serta simpan bukti pemenuhan. Status dana dan pengembalian mengikuti verifikasi penyedia serta hasil sengketa." sections={sections} />
    </PublicInfoShell>
  );
}
